### ISSUE TITLE
Sturmwind (.cdi) doesn't load

### ISSUE THREAD

**Issue by bigboo3000** [inolen/redream#181]
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=english bcast=ntsc
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Sturmwind (Unlicensed).cdi
cdi_parse version 3.5 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=352800 mode=CDDA/2352
cdi_parse_track track=2 fad=10031 off=23592912 mode=CDDA/2352
cdi_parse_track track=3 fad=21722 off=51090144 mode=CDDA/2352
cdi_parse_track track=4 fad=33745 off=79368240 mode=CDDA/2352
cdi_parse_track track=5 fad=49587 off=116628624 mode=CDDA/2352
cdi_parse_track track=6 fad=61134 off=143787168 mode=CDDA/2352
cdi_parse_track track=7 fad=79794 off=187675488 mode=CDDA/2352
cdi_parse_track track=8 fad=100317 off=235945584 mode=CDDA/2352
cdi_parse_track track=9 fad=111976 off=263367552 mode=CDDA/2352
cdi_parse_track track=10 fad=122983 off=289256016 mode=CDDA/2352
cdi_parse_track track=11 fad=135879 off=319587408 mode=CDDA/2352
cdi_parse_track track=12 fad=145095 off=341263440 mode=CDDA/2352
cdi_parse_track track=13 fad=158193 off=372069936 mode=CDDA/2352
cdi_parse_track track=14 fad=171863 off=404221776 mode=CDDA/2352
cdi_parse_track track=15 fad=184076 off=432946752 mode=CDDA/2352
cdi_parse_track track=16 fad=195739 off=460378128 mode=CDDA/2352
cdi_parse_track track=17 fad=204523 off=481038096 mode=CDDA/2352
cdi_parse_track track=18 fad=214647 off=504849744 mode=CDDA/2352
cdi_parse_track track=19 fad=220484 off=518578368 mode=CDDA/2352
cdi_parse_track track=20 fad=226014 off=531584928 mode=CDDA/2352
cdi_parse_track track=21 fad=231005 off=543323760 mode=CDDA/2352
cdi_parse_track track=22 fad=232805 off=547557360 mode=CDDA/2352
cdi_parse_track track=23 fad=233941 off=550229232 mode=CDDA/2352
cdi_parse_track track=24 fad=234671 off=551946192 mode=CDDA/2352
cdi_parse_track track=25 fad=254578 off=572305056 mode=M2F1/2336
disc_create id=Sturmwind DR001 V1.0 CD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
[C:\projects\redream\src\guest\gdrom\disc.c:95] Check failed: sector_fmt == GD_SECTOR_ANY || sector_fmt == track->sector_fmt

**Comment by inolen** [comment]
I _think_ this may be similar to https://github.com/inolen/redream/issues/91.

I thought #91 may not occur anymore since I set the time on boot automatically now, but this looks suspect.

Sturmwind boots for me, try booting to the bios and confirming that you don't get the "set the time" screen.

**Comment by bigboo3000** [comment]
When I boot to the bios I don't get a set the time screen. But the date is always 01/01/1950 0:00, even if I change it it's not saved.
![bios](https://user-images.githubusercontent.com/16479698/31319168-bc676b9a-ac5e-11e7-8bd2-763524eb2551.png)

**Comment by inolen** [comment]
@bigboo3000 interesting, this definitely feels related. There is code that should be setting that time to the current time on boot.

I just committed https://github.com/inolen/redream/commit/3cb912c1d0caa97cb8ad8e147a307ca270c8d5af. When you have time, could you check to see what that updated output looks like (I suspect time=0x0 for some reason).

**Comment by bigboo3000** [comment]
you're right

boot_load_rom loaded 'C:\Users\Loulou Lepoux\.redream\boot.bin'
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
bios_override_settings region=usa lang=french bcast=ntsc time=0x00000000
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Sturmwind (Unlicensed).cdi
cdi_parse version 3.5 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=352800 mode=CDDA/2352
cdi_parse_track track=2 fad=10031 off=23592912 mode=CDDA/2352
cdi_parse_track track=3 fad=21722 off=51090144 mode=CDDA/2352
cdi_parse_track track=4 fad=33745 off=79368240 mode=CDDA/2352
cdi_parse_track track=5 fad=49587 off=116628624 mode=CDDA/2352
cdi_parse_track track=6 fad=61134 off=143787168 mode=CDDA/2352
cdi_parse_track track=7 fad=79794 off=187675488 mode=CDDA/2352
cdi_parse_track track=8 fad=100317 off=235945584 mode=CDDA/2352
cdi_parse_track track=9 fad=111976 off=263367552 mode=CDDA/2352
cdi_parse_track track=10 fad=122983 off=289256016 mode=CDDA/2352
cdi_parse_track track=11 fad=135879 off=319587408 mode=CDDA/2352
cdi_parse_track track=12 fad=145095 off=341263440 mode=CDDA/2352
cdi_parse_track track=13 fad=158193 off=372069936 mode=CDDA/2352
cdi_parse_track track=14 fad=171863 off=404221776 mode=CDDA/2352
cdi_parse_track track=15 fad=184076 off=432946752 mode=CDDA/2352
cdi_parse_track track=16 fad=195739 off=460378128 mode=CDDA/2352
cdi_parse_track track=17 fad=204523 off=481038096 mode=CDDA/2352
cdi_parse_track track=18 fad=214647 off=504849744 mode=CDDA/2352
cdi_parse_track track=19 fad=220484 off=518578368 mode=CDDA/2352
cdi_parse_track track=20 fad=226014 off=531584928 mode=CDDA/2352
cdi_parse_track track=21 fad=231005 off=543323760 mode=CDDA/2352
cdi_parse_track track=22 fad=232805 off=547557360 mode=CDDA/2352
cdi_parse_track track=23 fad=233941 off=550229232 mode=CDDA/2352
cdi_parse_track track=24 fad=234671 off=551946192 mode=CDDA/2352
cdi_parse_track track=25 fad=254578 off=572305056 mode=M2F1/2336
disc_create id=Sturmwind DR001 V1.0 CD-ROM1/1
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
[C:\projects\redream\src\guest\gdrom\disc.c:95] Check failed: sector_fmt == GD_SECTOR_ANY || sector_fmt == track->sector_fmt

**Comment by inolen** [comment]
If you could go up further in `bios_local_time` and modify it to have a few extra printfs we may be able to debug a little further:
```
static uint32_t bios_local_time() {
  /* dreamcast system time is relative to 1/1/1950 00:00 */
  struct tm timeinfo;
  timeinfo.tm_year = 50;
  timeinfo.tm_mon = 0;
  timeinfo.tm_mday = 1;
  timeinfo.tm_hour = 0;
  timeinfo.tm_min = 0;
  timeinfo.tm_sec = 0;

  time_t base_time = mktime(&timeinfo);
  time_t curr_time = time(NULL);
  LOG_INFO("base=%s", ctime(&base_time));
  LOG_INFO("curr=%s", ctime(&curr_time));
  double delta = difftime(curr_time, base_time);
  LOG_INFO("delta=%f", delta);
  return (uint32_t)delta;
}
```

**Comment by bigboo3000** [comment]
I'm sorry but I don't know how to modify code and compile it.
I just download the compiled windows binary here
https://github.com/inolen/redream/releases

**Comment by inolen** [comment]
Alright, I've pushed some debug code to latest now that has those prints if you wanna give it a shot.

**Comment by bigboo3000** [comment]
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
base=(null)
curr=Sun Oct  8 21:26:36 2017

delta=0.000000
bios_override_settings region=usa lang=french bcast=ntsc time=0x00000000
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
dc_load no path supplied, loading bios

**Comment by inolen** [comment]
Interesting, I made a new commit that has a small chance at fixing this (https://github.com/inolen/redream/commit/6a4d1b036c48cdeec90374d48200316fb6fbd37c).

The build just completed.

**Comment by bigboo3000** [comment]
time still doesn't work but gamepad works now!

base=(null)
curr=Sun Oct  8 21:48:29 2017

delta=0.000000
bios_override_settings region=usa lang=french bcast=ntsc time=0x00000000
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
input_controller_added port=0 name=XInput Controller
dc_load no path supplied, loading bios
input_controller_added port=1 name=XInput Controller

**Comment by inolen** [comment]
This should be "fixed" with https://github.com/inolen/redream/commit/893cd0b0e48807aa7216be9b83e9b292fa2c439c.

I say "fixed" as #91 is still an issue, but you were only seeing this creep up due to the timestamp not being calculated correctly on Windows (which is now fixed).

**Comment by bigboo3000** [comment]
Yeah I just tested the fix. The date is now correct!
But:
1. time is off by 3h, it displays 20:40 in dreamcast BIOS while it's 23:40
2. sturmwind still doesn't boot and the problem is exactly the same

bios_override_settings region=usa lang=english bcast=ntsc time=0x7f792a53
audio_create_device latency=50 ms/2205 frames
imgui_update_font_tex w=512 h=64
input_controller_added port=0 name=XInput Controller
dc_load path=D:\Emulation\Archives\consoles_discs\dreamcast\Sturmwind (Unlicensed).cdi
cdi_parse version 3.5 detected
cdi_parse found 2 sessions
cdi_parse_track track=1 fad=150 off=352800 mode=CDDA/2352
cdi_parse_track track=2 fad=10031 off=23592912 mode=CDDA/2352
cdi_parse_track track=3 fad=21722 off=51090144 mode=CDDA/2352
cdi_parse_track track=4 fad=33745 off=79368240 mode=CDDA/2352
cdi_parse_track track=5 fad=49587 off=116628624 mode=CDDA/2352
cdi_parse_track track=6 fad=61134 off=143787168 mode=CDDA/2352
cdi_parse_track track=7 fad=79794 off=187675488 mode=CDDA/2352
cdi_parse_track track=8 fad=100317 off=235945584 mode=CDDA/2352
cdi_parse_track track=9 fad=111976 off=263367552 mode=CDDA/2352
cdi_parse_track track=10 fad=122983 off=289256016 mode=CDDA/2352
cdi_parse_track track=11 fad=135879 off=319587408 mode=CDDA/2352
cdi_parse_track track=12 fad=145095 off=341263440 mode=CDDA/2352
cdi_parse_track track=13 fad=158193 off=372069936 mode=CDDA/2352
cdi_parse_track track=14 fad=171863 off=404221776 mode=CDDA/2352
cdi_parse_track track=15 fad=184076 off=432946752 mode=CDDA/2352
cdi_parse_track track=16 fad=195739 off=460378128 mode=CDDA/2352
cdi_parse_track track=17 fad=204523 off=481038096 mode=CDDA/2352
cdi_parse_track track=18 fad=214647 off=504849744 mode=CDDA/2352
cdi_parse_track track=19 fad=220484 off=518578368 mode=CDDA/2352
cdi_parse_track track=20 fad=226014 off=531584928 mode=CDDA/2352
cdi_parse_track track=21 fad=231005 off=543323760 mode=CDDA/2352
cdi_parse_track track=22 fad=232805 off=547557360 mode=CDDA/2352
cdi_parse_track track=23 fad=233941 off=550229232 mode=CDDA/2352
cdi_parse_track track=24 fad=234671 off=551946192 mode=CDDA/2352
cdi_parse_track track=25 fad=254578 off=572305056 mode=M2F1/2336
disc_create id=Sturmwind DR001 V1.0 CD-ROM1/1
input_controller_added port=1 name=XInput Controller
sh4_ccn_reset
pvr_reconfigure_spg mode=VGA pixel_clock=13500000 line_clock=15734 vcount=262 hcount=857 interlace=0 vbstart=260 vbend=336
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=260 vbend=336
arm7_reset
sh4_ccn_reset
sh4_ccn_reset
sh4_ccn_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
arm7_reset
pvr_reconfigure_spg mode=NTSC pixel_clock=13500000 line_clock=31468 vcount=524 hcount=857 interlace=1 vbstart=516 vbend=36
[C:\projects\redream\src\guest\gdrom\disc.c:95] Check failed: sector_fmt == GD_SECTOR_ANY || sector_fmt == track->sector_fmt

**Comment by inolen** [comment]
Interesting, and I assume your local computer's clock is set to 23:40?

What's the md5 of your bios?

**Comment by bigboo3000** [comment]
Yes my computer's clock was 23:40, I don't think it's related to daylight saving time (and it's only one hour anyway) because with the debug build you made just before the time was displayed correctly in the log.

bios md5 : e10c53c2f8b90bab96ead2d368858623

**Comment by inolen** [comment]
Regarding the time, going to shelve looking at that until another date (feel free to open an issue about them being mismatched, I got lucky and it Worked On My Machine©). That feature exists to avoid getting the time nag screen, but it would be nice if they much up exactly.

We're on the same bios, so I'm just going to dive into #91 a bit more which does repro this issue for me.

**Comment by bigboo3000** [comment]
OK maybe San francisco RUSH 2049 is the same problem, even if it's gdi/chd and not cdi?
It works for you but not for me and it goes back to bios like this one..

**Comment by inolen** [comment]
The issue with RUSH may be related to me testing the USA version instead of the PAL version.

**Comment by bigboo3000** [comment]
OK I'll try USA version in the next days just to be sure.

**Comment by bigboo3000** [comment]
about time offset : I changed my system date to 31/10/2017 (winter time in Europe) and the offset between system time and dreamcast time is now 2 hours instead of 3 hours.

I think the problem in the code is  :
time_t curr_time_utc = mktime(**gmtime**(&curr_time_local));
I think it should be "localtime" instead of "gmtime" on windows

**Comment by literalmente-game** [comment]
I've tested the game with https://github.com/inolen/redream/commit/5e35a2649fc626378e3336f542fe7152925cdf15, we still have the same behavior.

**Comment by inolen** [comment]
Booted into Windows and finally managed to get a repro on this, which is both scary (the bios never reads the rtc it seems) but positive.

**Comment by inolen** [comment]
Fixed with 2dacdc06077250acfc58f8510dcea3ec6c0557ed

**Comment by bigboo3000** [comment]
The game now works but it keeps repeating this in the log:

mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x96018244
mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x9601823c
mem_unhandled_read addr=0x96018244

**Comment by literalmente-game** [comment]
@bigboo3000 does this affect the game in any way for you? This specific issue is solved (I was able to play the game for 10 minutes, 1st and 2nd level finished), the game is able to load and is very playable, for any other specific issue would be better to close this one and open another

**Comment by bigboo3000** [comment]
The game seems to work fine for me too. If this log isn't a problem I close the issue.

**Comment by inolen** [comment]
It's a problem that I'll keep an eye on. There is a bug in the arm interpreter spewing these messages in a lot of titles, I'm sure once it's fixed they'll all clear up.
